blank_issues_enabled: false
contact_links:
  - name: Homebridge Discord Channel for No-IP
    url: https://discord.gg/8fpZA4S
    about: Please ask and answer questions here.
  - name: @homebridge-plugins/homebridge-noip - Pull Requests
    url: https://github.com/homebridge-plugins/homebridge-noip/pulls
    about: Please report security vulnerabilities here.
